apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-svc
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: http-svc.dev
      http:
        paths:
          - backend:
              serviceName: http-svc
              servicePort: 80
